# Funding options for this project
# Uncomment and add your details if you want to enable GitHub Sponsors

# github: [Kristoffer93]
# patreon: your-username
# ko_fi: your-username
# custom: https://www.buymeacoffee.com/your-username
